# Generated by Django 4.2.5 on 2023-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='last_seen',
            field=models.CharField(default='Never', max_length=40),
        ),
    ]
