# Generated by Django 4.2.5 on 2023-09-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_alter_trader_gains'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='name',
            field=models.CharField(default='Lil Warren', max_length=40),
        ),
    ]
