# Generated by Django 4.2.5 on 2023-09-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_trader_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='gains',
            field=models.FloatField(default=0),
        ),
    ]
